In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
df=pd.read_csv("creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [41]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [29]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [42]:
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

## Over sampling and Under sampling

1. Oversampling — Duplicating samples from the minority class.

2. Undersampling — Deleting samples from the majority class.

In [43]:
x=df.drop("Class",axis=1)
y=df.Class

In [32]:
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.7)

In [46]:
log_class=LogisticRegression()
grid={"C":10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,shuffle=False,random_state=None)

In [36]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [47]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

C:\Users\bipla\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.82335184        nan 0.83825353        nan 0.84036735
        nan 0.83597939        nan 0.84064032]
  warnings.warn(
C:\Users\bipla\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [50]:
y_pred=clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85265    44]
 [   52    82]]
0.9988764439450862
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85309
           1       0.65      0.61      0.63       134

    accuracy                           1.00     85443
   macro avg       0.83      0.81      0.82     85443
weighted avg       1.00      1.00      1.00     85443



In [51]:
from sklearn.ensemble import RandomForestClassifier
classfier=RandomForestClassifier()
classfier.fit(x_train,y_train)

RandomForestClassifier()

In [52]:
y_pred=classfier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85303     6]
 [   33   101]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85309
           1       0.94      0.75      0.84       134

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## Under sampling => Remove/Reduce the data points belonging to the majority class 

preferable used for small sample set

In [55]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(.8)
x_train_ns,y_train_ns=ns.fit_resample(x_train,y_train)
print("before under sampling: Y value",format(Counter(y_train)))
print("after under sampling: Y value",format(Counter(y_train_ns)))

C:\Users\bipla\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


before under sampling: Y value Counter({0: 199006, 1: 358})
after under sampling: Y value Counter({0: 447, 1: 358})


In [58]:
## checking the result after under sampling
classfier=RandomForestClassifier()
classfier.fit(x_train_ns,y_train_ns)

RandomForestClassifier()

In [60]:
y_pred=classfier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[74280 11029]
 [   14   120]]
0.8707559425581967
              precision    recall  f1-score   support

           0       1.00      0.87      0.93     85309
           1       0.01      0.90      0.02       134

    accuracy                           0.87     85443
   macro avg       0.51      0.88      0.48     85443
weighted avg       1.00      0.87      0.93     85443



## Over sampling => Increasing the data points belonging to the minority class

In [61]:
from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(.5)
x_train_os,y_train_os=os.fit_resample(x_train,y_train)
print("before over sampling: Y value",format(Counter(y_train)))
print("after over sampling: Y value",format(Counter(y_train_os)))

C:\Users\bipla\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


before over sampling: Y value Counter({0: 199006, 1: 358})
after over sampling: Y value Counter({0: 199006, 1: 99503})


In [62]:
## checking the result after over sampling
classfier=RandomForestClassifier()
classfier.fit(x_train_os,y_train_os)
y_pred=classfier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85304     5]
 [   29   105]]
0.999602073897218
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85309
           1       0.95      0.78      0.86       134

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## SMOTE

SMOTE first selects a minority class instance a at random and 
finds its k nearest minority class neighbors.
The synthetic instance is then created by choosing one of the k nearest neighbors b at random and
connecting a and b to form a line segment in the feature space.
The synthetic instances are generated as a convex combination of the two chosen instances a and b.

The combination of SMOTE and under-sampling performs better than plain under-sampling.

In [63]:
from imblearn.combine import SMOTETomek

In [64]:
cs=SMOTETomek(.75)
x_train_cs,y_train_cs=cs.fit_resample(x_train,y_train)
print("before smote sampling: Y value",format(Counter(y_train)))
print("after smote sampling: Y value",format(Counter(y_train_cs)))

C:\Users\bipla\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


before smote sampling: Y value Counter({0: 199006, 1: 358})
after smote sampling: Y value Counter({0: 198312, 1: 148560})


In [ ]:
## checking the result after smote sampling
classfier=RandomForestClassifier()
classfier.fit(x_train_cs,y_train_cs)
y_pred=classfier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))