In [2]:
import numpy as np

In [3]:
a=[1,2,3,4]
type(a)

list

In [4]:
arr=np.array(a)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4])

In [7]:
arr.shape

(4,)

In [11]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
arr2=np.array([list1,list2,list3])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr2.shape

(3, 4)

In [13]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr2[2:,1:3]

array([[10, 11]])

In [23]:
d=np.arange(1,9,step=3)
d

array([1, 4, 7])

In [24]:
e=np.linspace(1,10,20)
e

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [37]:
array1=np.array(a)
array1
type(array1)

numpy.ndarray

In [40]:
copyarray=array1
copyarray
type(copyarray)

numpy.ndarray

In [42]:
#changing value by reference
copyarray[2:]=50
copyarray

array([ 1,  2, 50, 50])

In [43]:
array1

array([ 1,  2, 50, 50])

In [44]:
# copy function
copyarray2=array1.copy()
copyarray2

array([ 1,  2, 50, 50])

In [45]:
copyarray2[2:]=33
copyarray2

array([ 1,  2, 33, 33])

In [46]:
array1

array([ 1,  2, 50, 50])

In [49]:
#exploratory data analysis
array1[array1<40]

array([1, 2])

In [51]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [55]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [71]:
#random distribution
#A random distribution is a set of
#random numbers that follow a certain probability density function
#The probability is set by a number between 0 and 1,
# where 0 means that the value will never occur and 1 means that the value will always occur.
np.random.rand(3,4)

array([[0.16833973, 0.8247273 , 0.72314318, 0.37165092],
       [0.46794667, 0.54431934, 0.98893338, 0.26919312],
       [0.37717698, 0.2229059 , 0.44980422, 0.40913866]])

In [98]:
np.random.randn(3,3)

array([[-0.65202561,  1.58256416,  2.3446675 ],
       [-0.21251279, -0.86995293, -0.04724089],
       [-0.61781825, -1.46346874, -0.16666877]])

In [150]:
np.random.randint(1,100,8).reshape(2,4)

array([[53, 83, 89, 75],
       [91, 40, 61, 24]])